spring.application.name=api_projetos

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-projetos
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs